#!/usr/bin/env bash
# Display information about subdomains.

get_domain () {
	subdomain=$1
	domain=$2
	dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -1 | awk -v s="$subdomain" 'BEGIN { FS = " " } ; { print "The subdomain", s, "is a", $4, "record and points to", $5 }'
}
if [ $# -eq 1 ];
then
	domain="$1"
	
	get_domain "www" "$domain"
	get_domain "lb-01" "$domain"
	get_domain "web-01" "$domain"
	get_domain "web-02" "$domain"
elif [ $# -eq 2 ];
then
	get_domain "$2" "$1"
fi
