#!/usr/bin/env bash
# transfers a file from our client to a server.

if [ $# -gt 3 ]; then
	file_path=$1
	ip=$2
	user=$3
	key=$4

	scp -o StrictHostKeyChecking=no -i "$key" "$file_path" "${user}@${ip}":~/
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
