#!/usr/bin/env bash
# installs nginx and configures it

sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start

echo "Hello World!" > /var/www/html/index.html

sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
