#!/usr/bin/env bash

if ! command -V nginx >/dev/null;
then
	echo "Instaling Nginx"
	sudo apt-get update
	sudo apt-get install -y nginx
	sudo service nginx start
fi

echo "Hello World!" > /var/www/html/index.html

sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/site-available/default
