#!/usr/bin/env bash
# Sets up a Nginx server and configs /redirect_me redirection

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" > /var/www/html/index.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

sudo service nginx start
