#!/usr/bin/env bash
# Sets up a Nginx server and configs /redirect_me redirection

if ! command -v nginx > /dev/null;
then
	sudo apt-get update
	sudo apt-get install -y nginx
fi


echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null
content="server {
        listen 80 default_server;
	listen [::]:80 default_server;
	
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;      
	server_name _;
	location / {
		try_files \$uri \$uri/ =404;
	}
	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}
}"
path="/etc/nginx/sites-available/default"

if grep -q "location /redirect_me {" "$path";
then
	echo "$content" | sudo tee "$path" > /dev/null
	# echo "Successfully."
fi

sudo service nginx restart
sudo nginx -s reload
