#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that
#+ contains the string "Ceci n'est pas une page."

sudo apt-get -y update
sudo apt-get -y install nginx

echo "Hello World!" > /var/www/html/index.html

sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites_available/default
sudo mkdir -p /var/www/error
echo "Ceci n'est pas une page" | sudo tee /var/www/error/404.html
sudo sed -i '/server_name _/a error_page 404 /404 /404.html; location = /404.html {root /var/www/error/;internal;}' /etc/nginx/sites_avaibale/default
sudo service nginx start
