#!/usr/bin/env bash
# Generates a MySQL dump and creates a compressed archive out of it.

dt=$(date +"%d-%m-%Y")

mysqldump -u root -p"$1" --all-databases > backup.sql

tar -zcvf "$dt".tar.gz backup.sql
