#!/usr/bin/env bash
# Fixes Nginx listening port(80)

sudo rm -r /etc/nginx/sites-enabled/default

ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

sudo service nginx restart
sudo nginx -s reload
