#!/usr/bin/env bash
# apache2 debuging

if ! command -v apache2 > /dev/null;
then
	sudo apt-get update
	sudo apt-get install -y apache2
fi
sudo service apache2 restart

sudo chmod 644 /var/www/html/index.html
echo "Hello Holberton" > /var/www/html/index.html
