#!/usr/bin/env bash
# Restarts nginx as user "nginx"
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
pkill apache2
sudo chmod 644 /etc/nginx/nginx.conf
sudo --user nginx service nginx start
